name: Swap functional tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
    - master
    - main
    - develop
    - swap

jobs:
  job_functional_tests:
    uses: Zondax/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@swap-cosmos
    with:
      branch_for_polkadot: ${{ github.ref }}
      repo_for_polkadot: ${{ github.repository }}
      test_filter: '"Atom or atom or Cosmos or cosmos"'
