name: Swap functional tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
    - master
    - main
    - develop

jobs:
  job_functional_tests:
    uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@develop
    with:
      branch_for_cosmos: ${{ github.ref }}
      repo_for_cosmos: ${{ github.repository }}
      test_filter: '"ATOM or atom or Cosmos or cosmos"'
